In [22]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [23]:
xi = [435 , 11 , 86 ] 
w0 = 0
w = [1,1,1]

In [24]:

def dot(xi , w):
    n = len(xi)
    res = 0.0
    for i in range(n):
        res += xi[i] * w[i]
        return res

In [25]:
def linear_regression(xi):
    return w0 + dot(xi, w)

In [26]:
w_new = [w0] + w    

In [27]:
w_new 

[0, 1, 1, 1]

In [ ]:
xi = [435 , 11 , 86 ] 
w0 = 7.17
w = [0.01,0.04,0.002]
w_new = [w0] + w    

In [29]:
x1 = [1 , 148 , 24, 1385  ] 
x2 = [1 , 132 , 24, 2031  ] 
x10 = [1 , 453 , 11, 86  ] 

x = [x1 , x2 , x10]
x = np.array(x)
x


array([[   1,  148,   24, 1385],
       [   1,  132,   24, 2031],
       [   1,  453,   11,   86]])

In [74]:
def linear_regression(xi):
    return x.dot(w_new)

<H1 Training a linear regression model >

TRAININIG A LINEAR REGRESSION 

In [76]:
X= [[ 148 , 24, 1385  ],
    [ 132 , 24, 2031  ],
    [ 453 , 11, 86  ],
    [ 148 , 24, 1385  ],
    [ 132 , 74, 2031  ],
    [ 453 , 31, 86  ],
    [ 148 , 24, 1385  ],
    [ 132 , 54, 2031  ],
    [ 453 , 21, 86  ]
    ]
 


X = np.array(X)
X


array([[ 148,   24, 1385],
       [ 132,   24, 2031],
       [ 453,   11,   86],
       [ 148,   24, 1385],
       [ 132,   74, 2031],
       [ 453,   31,   86],
       [ 148,   24, 1385],
       [ 132,   54, 2031],
       [ 453,   21,   86]])

In [84]:
ones= np.ones(X.shape[0])
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [85]:
np.column_stack((ones,  X))

array([[1.000e+00, 1.480e+02, 2.400e+01, 1.385e+03],
       [1.000e+00, 1.320e+02, 2.400e+01, 2.031e+03],
       [1.000e+00, 4.530e+02, 1.100e+01, 8.600e+01],
       [1.000e+00, 1.480e+02, 2.400e+01, 1.385e+03],
       [1.000e+00, 1.320e+02, 7.400e+01, 2.031e+03],
       [1.000e+00, 4.530e+02, 3.100e+01, 8.600e+01],
       [1.000e+00, 1.480e+02, 2.400e+01, 1.385e+03],
       [1.000e+00, 1.320e+02, 5.400e+01, 2.031e+03],
       [1.000e+00, 4.530e+02, 2.100e+01, 8.600e+01]])

In [86]:
XTX = (X.T).dot(X)

In [91]:
y = [100 , 200 , 300 , 400 , 500 , 600 , 700 , 800 , 900]

In [92]:
XTX_inv = np.linalg.inv(XTX)

In [93]:
XTX.dot(XTX_inv).round()
print("XTX_inv shape:", XTX_inv.shape)
print("X.T shape:", X.T.shape)

XTX_inv shape: (3, 3)
X.T shape: (3, 9)


In [94]:
w_full = XTX_inv.dot(X.T).dot(y)

In [95]:
w0 = w_full[0]
w = w_full[1:]

In [96]:
w0 , w

(1.0157423428054202, array([6.86231361, 0.02551049]))

In [101]:
def train_linear_regression(x , y ) :
    ones = np.ones(x.shape[0])
    X = np.column_stack([ones, x])

    XTX = (X.T).dot(X)
    XTX_inv = np.linalg.inv(XTX)
    w_full = XTX_inv.dot(X.T).dot(y)
    w0 = w_full[0]
    w = w_full[1:]
    return w0 , w